import { ArrowRight, Activity, Terminal, Shield, CheckCircle2, Layout, HelpCircle } from "lucide-react";
import Link from "next/link";

export default function Home() {
  return (
    <div className="flex flex-col h-full bg-transparent overflow-hidden">
      <header className="h-[44px] border-b border-border flex items-center justify-between px-4 bg-[#050505] shrink-0">
        <div className="flex items-center gap-2">
          <div className="w-6 h-6 rounded-sm bg-primary/10 border border-primary/20 flex items-center justify-center">
            <Layout className="w-3.5 h-3.5 text-primary" />
          </div>
          <div>
            <h1 className="font-bold text-[13px] tracking-tight text-white/90">My Workspace <span className="text-zinc-600 font-normal mx-1">/</span> <span className="text-zinc-500 font-mono text-[10px]">Overview</span></h1>
          </div>
        </div>
      </header>

      <main className="flex-1 overflow-y-auto p-12 custom-scrollbar">
        {/* Hero / Welcome */}
        <div className="max-w-4xl mx-auto">
          <div className="mb-12">
            <div className="inline-flex items-center gap-2 px-2 py-0.5 rounded-sm bg-primary/10 border border-primary/20 mb-4 animate-in fade-in slide-in-from-bottom-2 duration-500">
              <span className="flex h-1.5 w-1.5 rounded-full bg-primary animate-pulse"></span>
              <span className="text-[9px] font-black tracking-[0.2em] uppercase text-primary">Intelligence Systems Active</span>
            </div>
            <h2 className="text-5xl font-black text-white tracking-tighter italic uppercase mb-4 animate-in fade-in slide-in-from-bottom-4 duration-500">
              ScanTrade <span className="text-zinc-700">Infrastructure</span>
            </h2>
            <p className="text-zinc-500 text-lg leading-relaxed max-w-2xl animate-in fade-in slide-in-from-bottom-6 duration-500">
              Welcome to your institutional-grade market intelligence workspace.
              Deploy scanners, analyze signal feeds, and manage Discord alerting pipes from a unified command center.
            </p>
          </div>

          {/* Quick Actions / Features */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-16 animate-in fade-in slide-in-from-bottom-8 duration-700">
            <Link href="/screeners" className="group p-6 rounded-sm bg-[#050505] border border-border hover:border-primary/50 transition-all shadow-xl">
              <Terminal className="w-6 h-6 text-primary mb-4 group-hover:scale-110 transition-transform" />
              <h3 className="text-sm font-black text-white uppercase tracking-widest mb-2 flex items-center justify-between">
                Market Scanners
                <ArrowRight className="w-3.5 h-3.5 opacity-0 group-hover:opacity-100 transition-opacity" />
              </h3>
              <p className="text-zinc-500 text-[11px] leading-relaxed">Execute high-frequency scanning logic across multiple asset classes.</p>
            </Link>

            <Link href="/master" className="group p-6 rounded-sm bg-[#050505] border border-border hover:border-primary/50 transition-all shadow-xl">
              <Activity className="w-6 h-6 text-primary mb-4 group-hover:scale-110 transition-transform" />
              <h3 className="text-sm font-black text-white uppercase tracking-widest mb-2 flex items-center justify-between">
                Signal Feed
                <ArrowRight className="w-3.5 h-3.5 opacity-0 group-hover:opacity-100 transition-opacity" />
              </h3>
              <p className="text-zinc-500 text-[11px] leading-relaxed">Unified stream of all intelligence generated by your deployed agents.</p>
            </Link>

            <Link href="/how-it-works" className="group p-6 rounded-sm bg-[#050505] border border-border hover:border-zinc-500 transition-all shadow-xl">
              <HelpCircle className="w-6 h-6 text-zinc-500 mb-4 group-hover:scale-110 transition-transform" />
              <h3 className="text-sm font-black text-white uppercase tracking-widest mb-2 flex items-center justify-between">
                Documentation
                <ArrowRight className="w-3.5 h-3.5 opacity-0 group-hover:opacity-100 transition-opacity" />
              </h3>
              <p className="text-zinc-500 text-[11px] leading-relaxed">Explore technical architecture and non-custodial safety protocols.</p>
            </Link>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 pt-12 border-t border-border/50 animate-in fade-in slide-in-from-bottom-10 duration-1000">
            <div className="flex gap-4 items-start">
              <div className="w-8 h-8 rounded-sm bg-zinc-800 flex items-center justify-center shrink-0">
                <Shield className="w-4 h-4 text-zinc-400" />
              </div>
              <div>
                <h4 className="text-xs font-black text-white uppercase tracking-widest mb-1">Non-Custodial Safety</h4>
                <p className="text-zinc-500 text-[11px] leading-relaxed">Your data remains within your own infrastructure. ScanTrade never manages or accesses your private capital.</p>
              </div>
            </div>
            <div className="flex gap-4 items-start">
              <div className="w-8 h-8 rounded-sm bg-zinc-800 flex items-center justify-center shrink-0">
                <CheckCircle2 className="w-4 h-4 text-zinc-400" />
              </div>
              <div>
                <h4 className="text-xs font-black text-white uppercase tracking-widest mb-1">Institutional Logic</h4>
                <p className="text-zinc-500 text-[11px] leading-relaxed">All alerts are verified against institutional-grade indicators (VWAP, RSI, MVWAP) before dispatch.</p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
